### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by Veronika-Rychla** [Petrasmej/Zivotopis#1]
Ahoj Petro,

dobrá práce, připojuji pár návrhů na zlepšení:

- [x] Barva textu černá a barva pozadí bílá jsou defaultně nastaveny v prohlížeči a není je třeba tedy definovat v elementu body znovu s těmito výchozími hodnotami. S klidem to umaž. 😎

- [x]  Vlastnost overflow: auto se nastavuje sekci, u obrázku je to již zbytečné, takže s klidem umaž, není třeba opakovat. 😉

- [ ]  Nevím, jestli jsem správně pochopila tvůj dotaz, ale pokud jde jen o prosté odsunutí obrázku více na střed s tvými současnými znalostmi, použij padding-right a hledej hodnotu, která se ti líbí. Případně pokročilejší nástroj je pozicování, viz toto video https://youtu.be/wrqXeLJyuys

```
.foto-CV{
    padding-right: 200px;
}
```

- [x] Na řádcích 26 a 27 ti v index.html chybí mezera před target="blank". Email nicméně tento atribut vůbec nepotřebuje, otevírá se v poštovní aplikaci, ne na nové kartě prohlížeče. 😌

**Bonusové poznámky:**

Chválím použití komentářů, dělají kód přehlednější pro případné budoucí kolegy v nové práci. 🤞

Dělat sloupce pomocí tabulky, pokud nemají logickou navazovací strukturu (jako třeba ceník) se nedělá, ale všechna čest, že ses s tím tak poprala, abys docílila požadovaného vzhledu. 😍 Pak uvidíš, jak jednoduše se tento problém dá řešit pomocí flexboxu, to bude magic. 😎 

Hezky dokazuješ, že méně je někdy více. Moderní weby jsou spíše minimalistické a šetří výraznými barvami. Přeplácanost je u webů na škodu. 🤩

**Comment by Petrasmej** [comment]
s tím obrázkem nemohu pohnout, pošlu to do slacku. 

ten kod je tady:
.foto-CV{
    width: 300px;
    float: right;
    border-radius: 20px;
    margin-left: 0;
    margin-right: 0;
    }

**Comment by Petrasmej** [comment]
Verčo, zkouším změny poslat do GITu a nedaří se mi,mam to tedy nejdřív pullnout? to jsem nikdy nedělala

To https://github.com/Petrasmej/Zivotopis.git
 ! [rejected]        main -> main (fetch first)
error: failed to push some refs to 'https://github.com/Petrasmej/Zivotopis.git'
hint: Updates were rejected because the remote contains work that you do       
hint: not have locally. This is usually caused by another repository pushing   
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

**Comment by Veronika-Rychla** [comment]
Vypracovávala jsi úkol na více počítačích? Třeba doma na desktopu a pak na laptopu jinde? To by vysvětlovalo tuhle chybovou hlášku a v takovém případě je třeba dát git pull, abych vždy měla aktuální verzi kódu na daném zařízení.

**Comment by Veronika-Rychla** [comment]
✅ SPLNĚNO ✅
